blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogListView.as_view(), name='blogs'),
    path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('bloggers/', views.AuthorListView.as_view(), name='authors'),
    path('blogger/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('blog/<int:pk>/create', views.BlogCommentCreateView.as_view(), name='create-comment-user'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('blog/', include('blog.urls')),
]

# add url maps to redirect the base url to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

# use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse

from django.utils import timezone

class Blog(models.Model):
    """Model representing a blog post."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    # Foreign Key used because blog can only have one author, but authors can have multiple blog posts.
    # Author as a string rather than object because it hasn't been declared yet in file.

    description = models.TextField(
        max_length=5000, help_text="Enter the description of the blog post")
    
    post_date = models.DateField(default=timezone.now)

    class Meta:
        ordering = ['-post_date']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('blog-detail', args=[str(self.id)])

import uuid # Required for unique book instances
from django.contrib.auth.models import User
class BlogComment(models.Model):

    """Model representing a specific comment of a blog."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular comment")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey(Blog, on_delete=models.RESTRICT, null=True)
    description = models.TextField(
        max_length=1000, help_text="Enter comment about blog here.")
    
    post_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['post_datetime']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.blog.title})'

class Author(models.Model):
    """Model representing an author."""
    name = models.CharField(max_length=100)
    bio = models.TextField(
        max_length=1000, help_text="Enter the bio of the author")
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

blog/forms.py
from django.forms import ModelForm
from blog.models import BlogComment

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class CreateCommentForm(ModelForm):
    def clean_description(self):
        data = self.cleaned_data['description']

        # Check if data is empty.
        if (not data):
            raise ValidationError(_('Invalid comment - comment is empty'))

        # Remember to always return the cleaned data.
        return data
    
    class Meta:
        model = BlogComment
        fields = ['description']
        help_texts = {'description': _('Enter comment about blog here.')}

blog/views.py
from typing import Any
from django.shortcuts import render

# Create your views here.
from .models import Blog, Author, BlogComment

def index(request):
    """View function for home page of the site."""
    num_blogs = Blog.objects.all().count()
    num_authors = Author.objects.count()
    num_comments = BlogComment.objects.count()

    context = {
        'num_blogs': num_blogs,
        'num_authors': num_authors,
        'num_comments': num_comments,
    }

    # Render the HTML template index.html with the data in context
    return render(request, 'index.html', context=context)

from django.views import generic

class BlogListView(generic.ListView):
    model = Blog
    paginate_by = 5

class BlogDetailView(generic.DetailView):
    model = Blog

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author


from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.urls import reverse

class BlogCommentCreateView(LoginRequiredMixin, CreateView):
    model = BlogComment
    fields = ["description"]

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.user = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        self.success_url = reverse('blog-detail', kwargs={'pk': self.kwargs['pk']})
        return super(BlogCommentCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BlogCommentCreateView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>DIY Mini Blog</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'blogs' %}">All blogs</a></li>
              <li><a href="{% url 'authors' %}">All bloggers</a></li>
              {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li>
                  <form id="logout-form" method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-link">Logout</button>
                  </form>
                </li>
             {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
             {% endif %}
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

blog/templates/blog/author_detail.html
{% extends "base_generic.html" %} 
{% block content %}
    <h1>Blogger: {{ author.name }}</h1>
    <h3>Bio</h3>
    <p>{{ author.bio }}</p>
    <h3>Blogs list</h3>
    {% if author.blog_set.all %}
        <ul>
          {% for blog in author.blog_set.all %}
          <li>
            <p>
                <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.post_date}})
            </p>
          </li>
          {% endfor %}
        </ul>
    {% else %}
        <p>There are no blogs from this blogger in the library.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>All bloggers</h1>
  {% if author_list %}
    <ul>
      {% for author in author_list %}
      <li>
        <p>
            <a href="{{ author.get_absolute_url }}">{{ author.name }}</a>
        </p>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no bloggers in the library.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ blog.title }}</h1>
  <p><strong>Post date:</strong> {{ blog.post_date }}</p>
  <p><strong>Author:</strong> <a href="{{ blog.author.get_absolute_url }}">{{ blog.author }}</a></p>
  <p><strong>Description:</strong></p>
  <p>{{ blog.description|linebreaks }}</p>
  
  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for comment in blog.blogcomment_set.all %}
      <hr />
      <p>
        {{ comment.user }} ({{ comment.post_datetime }}) - {{ comment.description }}
      </p>
    {% endfor %}
    <hr />
    {% if user.is_authenticated %}
      <p><a href="{% url 'create-comment-user' blog.id %}">Add a new comment</a></p>
    {% else %}
      <p><a href="{% url 'login' %}?next={{ request.path }}">Add a new comment</a></p>
    {% endif %}
  </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog List</h1>
  {% if blog_list %}
    <ul>
      {% for blog in blog_list %}
      <li>
        <p>
            <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a> ({{blog.post_date}}) -- 
            <a href="{{ blog.author.get_absolute_url }}">{{ blog.author }}</a></p>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no blogs in the library.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/blogcomment_form.html
{% extends "base_generic.html" %}

{% block content %}
  <p>Post your comment for: <a href="blog.get_absolute_url">{{ blog.title }}</a></p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>DIY Mini Blog Home</h1>
  <p>
    Welcome to DIY Mini Blog, a website developed as an assessment example on the
    <em>Mozilla Developer Network</em>!
  </p>
  <h2>Dynamic content</h2>
  <p>The blog site has the following record counts:</p>
  <ul>
    <li><strong>Blogs:</strong> {{ num_blogs }}</li>
    <li><strong>Bloggers:</strong> {{ num_authors }}</li>
    <li><strong>Blog Comments:</strong> {{ num_comments }}</li>
  </ul>
{% endblock %}